- name: "Docker setup,pull,and run the image"
  hosts: web
  tasks:
          - name: "docker yum repository"
            yum_repository:
                    name: "docker"
                    description: "docker rpm"
                    file: "docker"
                    baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
                    gpgcheck: no
          - name: "Docker Installation"
            package:
                    name: "docker-ce-18.09.1-3.el7.x86_64"
                    state: present
          - name: "Starting Docker service"
            service:
                    name: "docker"
                    state: started
                    enabled: yes
          - name: "Installing docker-py"
            command: "pip3 install docker"

          - name: "creating directory in managed Node"
            file:
                path: /root/webpages
                state: directory
          - name: "Copy to directory"
            copy:
                src: /root/playbooks/webpages/index.html
                dest: /root/webpages
 
          - name: "Pulling docker image"
            docker_image:
                    name: "httpd"
                    source: pull
          - name: "run docker container"
            docker_container:
                name: "Container1"
                image: httpd
                exposed_ports: 
                    - "80"
                ports:
                    - "8123:80"
                volumes:
                    - /root/webpages:/usr/local/apache2/htdocs
             
                    


